import {STARTERS,ROSTER,scaledStats} from '../data/roster.js';import {chooseStarter} from '../systems/save.js';import {uiBox,setVirtualHandler} from '../systems/ui.js';import {useLegacyLayout} from '../systems/resolution.js';
const Phaser = window.Phaser;
export class StarterScene extends Phaser.Scene{
  constructor(){super('StarterScene');}
  create(){useLegacyLayout(this);this.sel=0;this.cameras.main.setBackgroundColor('#314451');this.input.keyboard.on('keydown-LEFT',()=>this.move(-1));this.input.keyboard.on('keydown-RIGHT',()=>this.move(1));this.input.keyboard.on('keydown-ENTER',()=>this.choose());this.input.keyboard.on('keydown-SPACE',()=>this.choose());this.input.keyboard.on('keydown-ESC',()=>this.scene.start('TitleScene'));setVirtualHandler(this);this.render();}
  handleVirtualButton(k){if(k==='left')this.move(-1);if(k==='right')this.move(1);if(k==='a')this.choose();if(k==='b')this.scene.start('TitleScene');}
  move(d){this.sel=Phaser.Math.Wrap(this.sel+d,0,STARTERS.length);this.render();}
  render(){this.children.removeAll();this.add.text(120,9,'CHOOSE STARTER',{fontFamily:'monospace',fontSize:10,color:'#f8f0d8',fontStyle:'bold',stroke:'#111',strokeThickness:2}).setOrigin(.5);STARTERS.forEach((id,i)=>{const x=50+i*70,y=54,r=ROSTER[id];uiBox(this,x-29,y-28,58,70);this.add.image(x,y-2,'portrait_'+r.asset).setScale(.32);this.add.text(x,y+25,r.name.split(' ')[0].toUpperCase(),{fontFamily:'monospace',fontSize:6,color:i===this.sel?'#b41820':'#111',fontStyle:'bold'}).setOrigin(.5);if(i===this.sel)this.add.text(x,y-37,'▼',{fontFamily:'monospace',fontSize:11,color:'#ffe28a',stroke:'#111',strokeThickness:3}).setOrigin(.5);});const r=ROSTER[STARTERS[this.sel]],s=scaledStats(r.id,6);uiBox(this,12,124,216,27);this.add.text(20,129,`${r.name}  ${r.style}  HP${s.hp} ATK${s.atk} SPD${s.spd}`,{fontFamily:'monospace',fontSize:7,color:'#111'});this.add.text(20,141,'A SELECT   B BACK',{fontFamily:'monospace',fontSize:7,color:'#555',fontStyle:'bold'});}
  choose(){chooseStarter(STARTERS[this.sel]);this.scene.start('OverworldScene');}
}
