import {STARTERS,ROSTER,scaledStats,personaFor} from '../data/roster.js';import {chooseStarter} from '../systems/save.js';import {FONT,uiBox,setVirtualHandler} from '../systems/ui.js';
const Phaser = window.Phaser;
export class StarterScene extends Phaser.Scene{
  constructor(){super('StarterScene');}
  create(data={}){this.sel=0;this.story=!!data.story;this.returnArea=data.returnArea||'wrestlingroom';this.returnPos=data.returnPos||{x:10,y:6};this.cameras.main.setBackgroundColor('#314451');this.input.keyboard.on('keydown-LEFT',()=>this.move(-1));this.input.keyboard.on('keydown-RIGHT',()=>this.move(1));this.input.keyboard.on('keydown-ENTER',()=>this.choose());this.input.keyboard.on('keydown-SPACE',()=>this.choose());this.input.keyboard.on('keydown-ESC',()=>this.back());setVirtualHandler(this);this.render();}
  handleVirtualButton(k){if(k==='left')this.move(-1);if(k==='right')this.move(1);if(k==='a')this.choose();if(k==='b')this.back();}
  back(){this.scene.start(this.story?'OverworldScene':'TitleScene');}
  move(d){this.sel=Phaser.Math.Wrap(this.sel+d,0,STARTERS.length);this.render();}
  render(){this.children.removeAll();this.add.text(160,16,'CHOOSE YOUR PERSONA',{fontFamily:FONT,fontSize:14,color:'#f8f0d8',fontStyle:'bold',stroke:'#111',strokeThickness:3}).setOrigin(.5);STARTERS.forEach((id,i)=>{const x=64+i*96,y=82,r=ROSTER[id];uiBox(this,x-40,y-40,80,96);this.add.image(x,y-6,'portrait_'+r.asset).setScale(.44);this.add.text(x,y+30,r.name.split(' ')[0].toUpperCase(),{fontFamily:FONT,fontSize:11,color:i===this.sel?'#b41820':'#111',fontStyle:i===this.sel?'bold':'normal'}).setOrigin(.5);this.add.text(x,y+44,personaFor(id),{fontFamily:FONT,fontSize:10,color:'#6b39b4'}).setOrigin(.5);if(i===this.sel)this.add.text(x,y-52,'\u25bc',{fontFamily:FONT,fontSize:14,color:'#ffe28a',stroke:'#111',strokeThickness:3}).setOrigin(.5);});const r=ROSTER[STARTERS[this.sel]],s=scaledStats(r.id,6);uiBox(this,16,166,288,46);this.add.text(24,171,`${r.name} - ${personaFor(r.id)} persona`,{fontFamily:FONT,fontSize:11,color:'#111',fontStyle:'bold'});this.add.text(24,188,`${r.style}  COND ${s.hp}  STA ${s.stamina}  SPD ${s.spd}`,{fontFamily:FONT,fontSize:10,color:'#333'});}
  choose(){chooseStarter(STARTERS[this.sel],this.story?{story:true,area:this.returnArea,pos:this.returnPos}:{});this.scene.start('OverworldScene');}
}
