import {STARTERS,ROSTER,scaledStats,personaFor} from '../data/roster.js';import {chooseStarter} from '../systems/save.js';import {uiBox,setVirtualHandler} from '../systems/ui.js';
const Phaser = window.Phaser;
export class StarterScene extends Phaser.Scene{
  constructor(){super('StarterScene');}
  create(){this.sel=0;this.cameras.main.setBackgroundColor('#314451');this.input.keyboard.on('keydown-LEFT',()=>this.move(-1));this.input.keyboard.on('keydown-RIGHT',()=>this.move(1));this.input.keyboard.on('keydown-ENTER',()=>this.choose());this.input.keyboard.on('keydown-SPACE',()=>this.choose());this.input.keyboard.on('keydown-ESC',()=>this.scene.start('TitleScene'));setVirtualHandler(this);this.render();}
  handleVirtualButton(k){if(k==='left')this.move(-1);if(k==='right')this.move(1);if(k==='a')this.choose();if(k==='b')this.scene.start('TitleScene');}
  move(d){this.sel=Phaser.Math.Wrap(this.sel+d,0,STARTERS.length);this.render();}
  render(){this.children.removeAll();this.add.text(160,16,'CHOOSE YOUR STARTER',{fontFamily:'monospace',fontSize:13,color:'#f8f0d8',fontStyle:'bold',stroke:'#111',strokeThickness:3}).setOrigin(.5);STARTERS.forEach((id,i)=>{const x=64+i*96,y=82,r=ROSTER[id];uiBox(this,x-40,y-40,80,96);this.add.image(x,y-6,'portrait_'+r.asset).setScale(.44);this.add.text(x,y+32,r.name.split(' ')[0].toUpperCase(),{fontFamily:'monospace',fontSize:8,color:i===this.sel?'#b41820':'#111',fontStyle:'bold'}).setOrigin(.5);this.add.text(x,y+44,personaFor(id),{fontFamily:'monospace',fontSize:7,color:'#7a4ac9',fontStyle:'bold'}).setOrigin(.5);if(i===this.sel)this.add.text(x,y-52,'\u25bc',{fontFamily:'monospace',fontSize:14,color:'#ffe28a',stroke:'#111',strokeThickness:3}).setOrigin(.5);});const r=ROSTER[STARTERS[this.sel]],s=scaledStats(r.id,6);uiBox(this,16,166,288,46);this.add.text(24,174,`${r.name} - takes the mat as the ${personaFor(r.id)}`,{fontFamily:'monospace',fontSize:8,color:'#111',fontStyle:'bold'});this.add.text(24,187,`${r.style}  HP ${s.hp}  ATK ${s.atk}  SPD ${s.spd}`,{fontFamily:'monospace',fontSize:8,color:'#333'});this.add.text(24,199,'A SELECT   B BACK',{fontFamily:'monospace',fontSize:8,color:'#555',fontStyle:'bold'});}
  choose(){chooseStarter(STARTERS[this.sel]);this.scene.start('OverworldScene');}
}
